# Generated by Django 4.1.12 on 2023-10-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='adjust',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='advance',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='cheque_id',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='complete_status',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='pay_method',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='upi_id',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='estimate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
